// Real numbers from config.py, the SFT index on the Modal volume (sft_index.json),
// and a direct perplexity eval run against the SFT checkpoint (modal_app.py::eval_sft_perplexity).

export const sftPerplexity = {
  value: 8.11,
  loss: 2.0935,
  scoredTokens: 100_659,
  numExamples: 1_196,
  note: "Computed on assistant-response tokens only (the loss-masked span), averaged over the full SFT set. sft_train has no held-out split, so this is a train-set number, not a generalization measure.",
};

export const qaDataset = {
  totalPairs: 1_196,
  droppedTooLong: 0,
  domainCounts: [
    { domain: "Legal", key: "legal", count: 656 },
    { domain: "SEC filings", key: "sec", count: 300 },
    { domain: "General", key: "general", count: 240 },
  ],
  generatorModel: "gpt-5.4-nano",
  note: "QA pairs generated by an LLM grounded in excerpts from the pretraining corpus, weighted to roughly match the legal-first pretrain mix (~55/25/20).",
};

export const sftTraining = {
  epochs: 2,
  lr: 5e-5,
  microBatchSize: 16,
  optimizer: "AdamW (weight_decay=0.1)",
  gpuType: "1x NVIDIA L4 (Modal)",
  startedFrom: "pretrained base checkpoint (slm-125m-base)",
};

// Base -> SFT head-to-head on CaseHOLD (casehold/casehold, "all" config, test split),
// computed directly against both checkpoints (modal_app.py::eval_casehold). CaseHOLD was
// explicitly excluded from the pretraining corpus during decontamination (see
// config.EVAL_HOLDOUT / _build_contamination_ngrams in modal_app.py), so it's a genuine
// held-out benchmark, not something either checkpoint could have memorized.
export const caseholdComparison = {
  task: "CaseHOLD (5-way multiple choice, held out of pretraining)",
  nExamples: 500,
  randomBaseline: 0.2,
  base: { acc: 0.094, accNorm: 0.17 },
  sft: { acc: 0.096, accNorm: 0.166 },
  deltaAccNorm: 0.166 - 0.17,
  note: "Each checkpoint scores the 5 candidate holdings by length-normalized log-likelihood (no chat template on either side, so base and SFT are scored on the identical completion task). Both sit at or below the 20% random baseline — expected for a 125M-parameter model trained on ~2B tokens on a single-digit-dollar budget, and SFT (2 epochs on 1,196 QA pairs) was aimed at instruction-following, not this likelihood-comparison format, so it neither helps nor hurts here.",
};

export type QASample = { domain: string; prompt: string; response: string };

export const qaSamples: QASample[] = [
  {
    domain: "legal",
    prompt: "What events involving the airport permits took place from 1971 through the CUP expiration in 1973?",
    response:
      "The excerpt states that Lang acquired the property in 1971 and was granted a two-year CUP to operate a private airport used mainly for agricultural flights. In 1972, the Sacramento County General Plan was amended to allow a public use airport at the location, and Lang acquired a state airport permit for that purpose. The CUP expired in 1973. Lang did not apply for renewal, but continued operating the airport.",
  },
  {
    domain: "legal",
    prompt: "What did the court say regarding the admission of a sawed-off shotgun as evidence?",
    response:
      "The defendant argued that the prosecutor failed to connect the gun sufficiently to him or to the charged crime. The court rejected this contention, stating there was no merit because the gun was connected both to the defendant and to the robbery.",
  },
  {
    domain: "legal",
    prompt: "How did the District Court instruct the jury regarding Dutton's expert testimony?",
    response:
      "The excerpt states that although the District Court allowed Dutton to testify, it gave the jury a cautionary instruction. Specifically, the instruction told the jury that Dutton's testimony could not be used as substantive evidence or as her opinion that Robins had committed the alleged crimes.",
  },
  {
    domain: "sec",
    prompt: "When was Parlux Fragrances, Inc. incorporated, and in which state?",
    response: "Parlux Fragrances, Inc. (the Company) was incorporated in Delaware in 1984.",
  },
  {
    domain: "sec",
    prompt: "What ATM-related services does the Company provide and how many ATMs does it process for?",
    response:
      "The Company also provides automated teller machine (“ATM”) Services. These consist of owning and operating the MAC-branded electronic funds transfer network and processing for approximately 39,000 ATMs nationwide. Of these, the Company owns approximately 1,000 ATMs.",
  },
  {
    domain: "sec",
    prompt: "What does the excerpt say about XML's role in EPS products?",
    response:
      "The excerpt says EPS products participate in worldwide standards development for XML, and that XML is widely endorsed and currently the most accepted standard for data distribution and interchange over the Web. It also states that EPS products' use of XML helps users find and sort complex information and present user-specific, dynamically generated information on demand, including assembling a customized “virtual document” based on criteria such as user preference, profile, and browser.",
  },
  {
    domain: "general",
    prompt: "What words are spoken during the imposition of ashes on Ash Wednesday, and what do they signify?",
    response:
      "During the imposition of ashes, the Pastor speaks: “For dust you are and to dust you shall return” (Genesis 3:19). The excerpt explains that these are the words God spoke to Adam and Eve after they ate the forbidden fruit and fell into sin, indicating “the bitterest fruit of their sin, namely death.” In the Ash Wednesday context, the words remind the penitent of sinfulness and mortality, emphasizing the need to repent and get right with God before it is too late.",
  },
  {
    domain: "general",
    prompt: "What is hyperglycemia, and why is sustained hyperglycemia concerning?",
    response:
      "Hyperglycemia is the state the body goes into when blood sugar levels exceed the excerpt's thresholds (greater than 100 mg/dL during fasting or greater than 120 mg/dL for the two hours after a meal). The excerpt says an occasional case of hyperglycemia is not harmful, but sustained or frequent hyperglycemia is a cause for alarm. It can result in damage to multiple body parts and systems, including the vascular system, the brain, the kidneys, the eyes, and the nervous system.",
  },
  {
    domain: "general",
    prompt: "How does the technical support staff handle repairs when a remote solution isn't sufficient?",
    response:
      "If needed, the technical support staff person may visit the staff member to solve the problem or deliver a replacement device. Sometimes he will seek help from IT management or a vendor to complete the repair.",
  },
];

export const sftModelMeta = {
  hfRepo: "IndraniBera/slm-125m-sft",
  hfUrl: "https://huggingface.co/IndraniBera/slm-125m-sft",
  hfPrivate: true,
  baseRepo: "IndraniBera/slm-125m-base",
};
